spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
        hbm2ddl:
          auto: create-drop

#server:
#  ssl:
#    key-store: classpath:ssh/dev-keystore.p12
#    key-store-type: PKCS12
#    key-alias: dev-keystore
#    key-store-password: 123456

#logging:
#  level:
#    org.hibernate.type.descriptor.sql : trace

logging:
  level:
    root: info
