spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:11731/chat_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate

server:
  ssl:
    key-store: classpath:ssl/dev-keystore.p12
    key-store-type: PKCS12
    key-alias: dev-keystore
    key-store-password: 123456
