spring:
  config:
    activate:
      on-profile: stage
  datasource:
    url: jdbc:mysql://localhost:11731/chat_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
        hbm2ddl:
          auto: validate
