services:
  clover-chat-server:
    image: ghcr.io/jongho445/clover-chat-server:latest
    container_name: clover-chat-server
    working_dir: /usr/src/app
    entrypoint: java -jar ./build/libs/clover-chat-server-0.0.1-SNAPSHOT.jar
    environment:
      spring.profiles.active: prod
      spring.datasource.url: jdbc:mysql://141.164.37.168:11731/chat_db
    ports:
      - "11730:11730"