services:
  chat-nginx:
    image: "ewr.vultrcr.com/${REGISTRY}/chat-nginx:latest"
    container_name: chat-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
    networks:
      - my-net
  chat-server:
    image: "ewr.vultrcr.com/${REGISTRY}/chat-server:latest"
    container_name: chat-server
    working_dir: /app
    entrypoint: bash -c "sleep 30; java -jar ./app.jar"
    environment:
      spring.profiles.active: prod
      spring.datasource.url: "jdbc:mysql://${DB_ENDPOINT}/chat_db"
    ports:
      - "8080:8080"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
