services:
  chat-db:
    image: "ewr.vultrcr.com/${REGISTRY}/chat-db:latest"
    container_name: chat-db
    ports:
      - "11731:11731"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "chat_db"
      MYSQL_TCP_PORT: 11731
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - my-net
  chat-nginx:
    image: "ewr.vultrcr.com/${REGISTRY}/chat-nginx:latest"
    container_name: chat-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
    networks:
      - my-net
  chat-server:
    image: "ewr.vultrcr.com/${REGISTRY}/chat-server:latest"
    container_name: chat-server
    working_dir: /app
    entrypoint: bash -c "sleep 30; java -jar ./server.jar"
    environment:
      spring.profiles.active: prod
      spring.datasource.url: jdbc:mysql://chat-db:11731/chat_db
    ports:
      - "8080:8080"
    networks:
      - my-net
    depends_on:
      - chat-nginx
      - chat-db

networks:
  my-net:
    driver: bridge
