services:
  nginx:
    image: nginx:1.25.4
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "11730:11730"
    volumes:
      - ./assets/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./assets/nginx/dist:/app/gui
      - ./assets/nginx/index.html:/app/gui/index.html
      - ./secret/fullchain.pem:/app/secret/fullchain.pem
      - ./secret/privkey.pem:/app/secret/privkey.pem
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
