services:
  nginx:
    image: nginx:1.25.4
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "11731:11731"
    volumes:
      - ./assets/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./assets/nginx/dist:/app/gui
