services:
  chat-db:
    image: chat-db:latest
    container_name: chat-db
    ports:
      - "11731:11731"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "chat_db"
      MYSQL_TCP_PORT: 11731
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
